# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.04.23
_src_path: gh:scientific-python/cookie
backend: hatch
email: kratsg@gmail.com
full_name: Giordon Stark
license: Apache
org: scipp-atlas
project_name: atlas
project_short_description: Helper python package for ATLAS HEP work.
url: https://github.com/scipp-atlas/atlas
vcs: true
